kind = "DojoContract"
class_hash = "0x631fb27174f0ae1323a18bb6d3fef36298eedee2bda24287f4565d8d618b844"
original_class_hash = "0x631fb27174f0ae1323a18bb6d3fef36298eedee2bda24287f4565d8d618b844"
base_class_hash = "0x0"
abi = "manifests/dev/abis/base/contracts/shard_dungeon_systems_hazard_hall_hazard_hall.json"
reads = []
writes = []
computed = []
init_calldata = []
name = "shard_dungeon::systems::hazard_hall::hazard_hall"
